server.port=8080
spring.application.name=sysml-parser
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

app.basefilepath=C:/Users/pedro/Downloads/sysml/src/main/java/sysml
app.systemlibpath=C:/Users/pedro/git/new pilot install/SySML-v2-Pilot-Implementation/sysml.library
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true